# Installer for clipboard2keystroke (Windows).
#
#   irm https://raw.githubusercontent.com/akshath/clipboard2keystroke/main/install.ps1 | iex
#
# Environment variables:
#   C2K_REF      git ref to install from  (default: main)
#   C2K_DIR      install directory        (default: %LOCALAPPDATA%\clipboard2keystroke)
#
# Uninstall:
#   & ([scriptblock]::Create((irm https://raw.githubusercontent.com/akshath/clipboard2keystroke/main/install.ps1))) -Uninstall

param([switch]$Uninstall)

$ErrorActionPreference = 'Stop'

$repo    = 'akshath/clipboard2keystroke'
$ref     = if ($env:C2K_REF) { $env:C2K_REF } else { 'main' }
$dir     = if ($env:C2K_DIR) { $env:C2K_DIR } else { Join-Path $env:LOCALAPPDATA 'clipboard2keystroke' }
$rawUrl  = "https://raw.githubusercontent.com/$repo/$ref/clipboard2keystroke.py"
$script  = Join-Path $dir 'clipboard2keystroke.py'
$shim    = Join-Path $dir 'clipboard2keystroke.cmd'

function Add-ToUserPath($path) {
    $current = [Environment]::GetEnvironmentVariable('Path', 'User')
    if ($current -split ';' -contains $path) { return $false }
    $new = if ([string]::IsNullOrEmpty($current)) { $path } else { "$current;$path" }
    [Environment]::SetEnvironmentVariable('Path', $new, 'User')
    return $true
}

function Remove-FromUserPath($path) {
    $current = [Environment]::GetEnvironmentVariable('Path', 'User')
    if (-not $current) { return }
    $kept = $current -split ';' | Where-Object { $_ -and $_ -ne $path }
    [Environment]::SetEnvironmentVariable('Path', ($kept -join ';'), 'User')
}

if ($Uninstall) {
    if (Test-Path $dir) { Remove-Item -Recurse -Force $dir }
    Remove-FromUserPath $dir
    Write-Host "Removed $dir (uv was left installed)."
    return
}

# --- uv ---------------------------------------------------------------------
function Find-Uv {
    $cmd = Get-Command uv -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    $candidate = Join-Path $env:USERPROFILE '.local\bin\uv.exe'
    if (Test-Path $candidate) { return $candidate }
    return $null
}

$uv = Find-Uv
if (-not $uv) {
    Write-Host 'uv not found, installing it from astral.sh ...'
    irm https://astral.sh/uv/install.ps1 | iex
    $env:Path = [Environment]::GetEnvironmentVariable('Path', 'User') + ';' + $env:Path
    $uv = Find-Uv
    if (-not $uv) { throw 'uv install finished but uv was not found; install it manually: https://docs.astral.sh/uv/' }
}

# --- script -----------------------------------------------------------------
New-Item -ItemType Directory -Force -Path $dir | Out-Null

Write-Host "Downloading clipboard2keystroke ($ref) ..."
$tmp = Join-Path ([IO.Path]::GetTempPath()) ("clipboard2keystroke-" + [guid]::NewGuid() + '.py')
Invoke-WebRequest -Uri $rawUrl -OutFile $tmp -UseBasicParsing

$firstLine = (Get-Content $tmp -TotalCount 1)
if ($firstLine -ne '# /// script') {
    Remove-Item -Force $tmp
    throw "downloaded file does not look like clipboard2keystroke.py; check that ref '$ref' exists"
}
Move-Item -Force $tmp $script

# --- launcher ---------------------------------------------------------------
@"
@echo off
REM Generated by the clipboard2keystroke installer.
"$uv" run --script "$script" %*
"@ | Set-Content -Path $shim -Encoding ASCII

Write-Host ''
Write-Host "Installed clipboard2keystroke to $shim"

if (Add-ToUserPath $dir) {
    Write-Host "Added $dir to your user PATH - open a new terminal, then run:  clipboard2keystroke"
} else {
    Write-Host 'Run it with:  clipboard2keystroke'
}
