#!/bin/sh
# Installer for clipboard2keystroke (macOS / Linux).
#
#   curl -fsSL https://raw.githubusercontent.com/akshath/clipboard2keystroke/main/install.sh | sh
#
# Environment variables:
#   C2K_REF      git ref to install from   (default: main)
#   C2K_BIN_DIR  where the launcher goes   (default: ~/.local/bin)
#   C2K_LIB_DIR  where the script goes     (default: ~/.local/share/clipboard2keystroke)

set -eu

REPO="akshath/clipboard2keystroke"
REF="${C2K_REF:-main}"
BIN_DIR="${C2K_BIN_DIR:-$HOME/.local/bin}"
LIB_DIR="${C2K_LIB_DIR:-$HOME/.local/share/clipboard2keystroke}"
RAW_URL="https://raw.githubusercontent.com/$REPO/$REF/clipboard2keystroke.py"
LAUNCHER="$BIN_DIR/clipboard2keystroke"

say() { printf '%s\n' "$*"; }
err() { printf 'error: %s\n' "$*" >&2; exit 1; }

usage() {
	cat <<EOF
Install clipboard2keystroke.

Usage: install.sh [--uninstall] [--help]

  --uninstall   remove the launcher and installed script
  --help        show this message
EOF
}

download() {
	# download <url> <dest>
	if command -v curl >/dev/null 2>&1; then
		curl -fsSL "$1" -o "$2"
	elif command -v wget >/dev/null 2>&1; then
		wget -qO "$2" "$1"
	else
		err "neither curl nor wget is available"
	fi
}

uninstall() {
	rm -f "$LAUNCHER"
	rm -rf "$LIB_DIR"
	say "Removed $LAUNCHER and $LIB_DIR"
	say "uv was left installed."
	exit 0
}

ensure_uv() {
	if command -v uv >/dev/null 2>&1; then
		UV="$(command -v uv)"
		return
	fi
	if [ -x "$HOME/.local/bin/uv" ]; then
		UV="$HOME/.local/bin/uv"
		return
	fi

	say "uv not found, installing it from astral.sh ..."
	if command -v curl >/dev/null 2>&1; then
		curl -LsSf https://astral.sh/uv/install.sh | sh
	elif command -v wget >/dev/null 2>&1; then
		wget -qO- https://astral.sh/uv/install.sh | sh
	else
		err "neither curl nor wget is available"
	fi

	if command -v uv >/dev/null 2>&1; then
		UV="$(command -v uv)"
	elif [ -x "$HOME/.local/bin/uv" ]; then
		UV="$HOME/.local/bin/uv"
	else
		err "uv install finished but uv was not found; install it manually: https://docs.astral.sh/uv/"
	fi
}

case "${1:-}" in
	--uninstall) uninstall ;;
	--help | -h) usage; exit 0 ;;
	"") ;;
	*) err "unknown option: $1" ;;
esac

ensure_uv

mkdir -p "$LIB_DIR" "$BIN_DIR"

tmp="$(mktemp "${TMPDIR:-/tmp}/clipboard2keystroke.XXXXXX")"
trap 'rm -f "$tmp"' EXIT INT TERM

say "Downloading clipboard2keystroke ($REF) ..."
if ! download "$RAW_URL" "$tmp"; then
	err "download failed: $RAW_URL (check that ref '$REF' exists)"
fi
[ -s "$tmp" ] || err "downloaded file is empty; check that ref '$REF' exists"
head -n 1 "$tmp" | grep -q '^# /// script' || err "downloaded file does not look like clipboard2keystroke.py"

mv "$tmp" "$LIB_DIR/clipboard2keystroke.py"
trap - EXIT INT TERM
chmod 644 "$LIB_DIR/clipboard2keystroke.py"

cat >"$LAUNCHER" <<EOF
#!/bin/sh
# Generated by the clipboard2keystroke installer.
exec "$UV" run --script "$LIB_DIR/clipboard2keystroke.py" "\$@"
EOF
chmod 755 "$LAUNCHER"

say ""
say "Installed clipboard2keystroke to $LAUNCHER"

case ":${PATH}:" in
	*":$BIN_DIR:"*) say "Run it with:  clipboard2keystroke" ;;
	*)
		say ""
		say "$BIN_DIR is not on your PATH. Add it:"
		say "  echo 'export PATH=\"$BIN_DIR:\$PATH\"' >> ~/.zshrc   # or ~/.bashrc"
		say ""
		say "Or run it directly:  $LAUNCHER"
		;;
esac

case "$(uname -s)" in
	Darwin)
		say ""
		say "macOS: the first run needs Accessibility permission for your terminal"
		say "(System Settings > Privacy & Security > Accessibility)."
		;;
	Linux)
		say ""
		say "Linux: the 'keyboard' backend needs root, so run it with sudo:"
		say "  sudo $LAUNCHER"
		;;
esac
